import { randomUUID } from "node:crypto"
import { mkdir, rename, rm, writeFile } from "node:fs/promises"
import { join, relative } from "node:path"

import { resolvePresets } from "@hokit/config/resolve-presets"
import { resolveProjectPath } from "@hokit/filesystem/resolve-project-path"
import { loadModules } from "@hokit/loader/load-modules"
import { storage } from "@hokit/metadata"
import { scanModules } from "@hokit/scanner/scan-modules"
import type { BuildConfig, ScannedSnippet } from "@hokit/types"

interface DocumentedSnippet {
    preset: string
    snippet: ScannedSnippet
}

function slug(value: string) {
    return value.toLowerCase().replaceAll(/[^a-z0-9_-]+/g, "-")
}

async function writeDocument(path: string, content: string) {
    const temporary = `${path}.${randomUUID()}.tmp`
    try {
        await writeFile(temporary, content, { flag: "wx", mode: 0o600 })
        await rename(temporary, path)
    } catch (error) {
        await rm(temporary, { force: true })
        throw error
    }
}

function renderSnippet(root: string, entry: DocumentedSnippet) {
    const { snippet, preset } = entry
    const status = snippet.todo ? `Pending — ${snippet.todo}` : "Available"
    const source = snippet.location
        ? `${relative(root, snippet.location.file)}:${snippet.location.line}`
        : "Unknown"

    return `## ${snippet.config.name}

- **Preset:** ${preset}
- **Prefix:** \`${snippet.config.prefix}\`
- **Status:** ${status}
- **Source:** \`${source}\`
- **Description:** ${snippet.config.description ?? snippet.config.name}

~~~~text
${snippet.config.body.join("\n")}
~~~~
`
}

export async function generateDocs(config: BuildConfig, root = process.cwd()) {
    const modulesDirectory = resolveProjectPath(root, config.cwd, {
        allowRoot: true
    })
    const output = resolveProjectPath(
        root,
        config.docs?.output ?? "docs/snippets"
    )
    const title = config.docs?.title ?? "Hokit Snippets"

    storage.clear()
    await loadModules(modulesDirectory)
    const modules = scanModules()
    const presets = resolvePresets(config)
    const groups = new Map<string, DocumentedSnippet[]>()

    for (const module of modules) {
        const preset = presets[module.module.preset]
        if (!preset) continue

        for (const scope of preset.scopes) {
            const entries = groups.get(scope) ?? []
            entries.push(
                ...module.snippets.map((snippet) => ({
                    preset: module.module.preset,
                    snippet
                }))
            )
            groups.set(scope, entries)
        }
    }

    await mkdir(output, { recursive: true })
    const rows: string[] = []

    for (const [scope, entries] of [...groups].sort(([a], [b]) =>
        a.localeCompare(b)
    )) {
        const filename = `${slug(scope)}.md`
        const pending = entries.filter((entry) => entry.snippet.todo).length
        rows.push(
            `| [${scope}](./${filename}) | ${entries.length} | ${pending} |`
        )
        const content = `# ${title}: ${scope}

[← Back to summary](./README.md)

${entries.map((entry) => renderSnippet(root, entry)).join("\n")}`
        await writeDocument(join(output, filename), content)
    }

    const index = `# ${title}

Documentation generated by Hokit.

| Scope | Snippets | Pending |
| --- | ---: | ---: |
${rows.join("\n")}
`
    const indexPath = join(output, "README.md")
    await writeDocument(indexPath, index)

    return {
        index: indexPath,
        pages: groups.size,
        snippets: modules.flatMap((module) => module.snippets).length
    }
}
